/**
 * Captured Defects column lists (no tokens) used when preference is still
 * on another project's defectFilter. PUT body is { defectFilter } only.
 */
module.exports = {
  5: [
  {
    "originalLabel": "Id",
    "label": "ID",
    "key": "code",
    "controlType": "TEXT",
    "hasMap": false,
    "cellCssClass": "badge-id",
    "width": 175,
    "deleted": false,
    "shownIn": [
      "TABLE"
    ],
    "sort": true,
    "sortType": "dsc",
    "showProfileIcon": false,
    "filter": true,
    "type": "",
    "keyname": "",
    "parentId": 9,
    "seq": 1,
    "jsonArrayKey": "",
    "fieldType": "defaultFld",
    "mandatory": false,
    "readOnly": false,
    "multi": false,
    "isDefault": true,
    "minLimit": 0,
    "maxLimit": 0,
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "55e0a060-c5ae-4270-8c3d-67cd0d0dcee8",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Name",
    "label": "Name",
    "key": "name",
    "controlType": "TEXT",
    "hasMap": false,
    "parentId": 9,
    "seq": 2,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": true,
    "jsonArrayKey": "",
    "minLimit": 3,
    "maxLimit": 500,
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "cd494001-0d14-40da-afcc-7b69629c0410",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Module",
    "label": "Module",
    "key": "moduleId",
    "controlType": "MODULE-LIST",
    "hasMap": true,
    "displayKey": {
      "field": "name"
    },
    "parentId": 9,
    "seq": 7,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "d91d8f28-4bfe-45e9-b47b-b29781e4199c",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "State",
    "label": "State",
    "key": "state",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 4,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": true,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "1f1e5e1d-bd25-4856-a3f4-d031f0cf9142",
    "projectId": 5,
    "createdBy": 2,
    "limit": 0,
    "updatedBy": 71,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Labels",
    "label": "Labels",
    "key": "tags",
    "controlType": "LABEL",
    "multi": true,
    "hasMap": true,
    "displayKey": {
      "field": "name"
    },
    "jsonArrayKey": "",
    "parentId": 9,
    "seq": 8,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "",
    "type": "",
    "isDefault": true,
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "a90bb005-0d33-4058-b557-6b5c0d87d884",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Category",
    "label": "Category",
    "key": "category",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 14,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "f0ccd1e1-0118-4eb6-b6bf-de98b3631cf8",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Priority",
    "label": "Priority",
    "key": "priority",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 5,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "2c158a40-2bfc-484a-90a5-d918864b1832",
    "projectId": 5,
    "createdBy": 2,
    "limit": 0,
    "updatedBy": 71,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Test Case",
    "label": "Test Case",
    "key": "selectedTestCase",
    "controlType": "LIST",
    "multi": true,
    "hasMap": true,
    "displayKey": {
      "field": "name",
      "field2": "code"
    },
    "jsonArrayKey": "",
    "parentId": 9,
    "seq": 12,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "id",
    "type": "ARRAYKEYS",
    "isDefault": false,
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "ab622f5e-b447-4cb6-beb1-c15dab9ce777",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Created On",
    "label": "Created On",
    "key": "createdAt",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 29,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "shownIn": [
      "TABLE",
      "EDIT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "e4c436b5-159d-4134-8baa-0a68ad146f8b",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Updated On",
    "label": "Updated On",
    "key": "updatedAt",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 30,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "shownIn": [
      "TABLE",
      "EDIT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "ad4ee7c0-ff3d-4788-bef0-35af41817795",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Closed Date",
    "label": "Closed Date",
    "key": "closedDate",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 23,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE"
    ],
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "bbb42701-d11b-4f5d-85c9-989f92204b4c",
    "projectId": 5,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "id": "3f7d69be-1055-40ef-8689-7bae1df3cc66",
    "deleted": false,
    "projectId": 5,
    "cellCssClass": "",
    "controlType": "LIST",
    "createdBy": 71,
    "customFldType": "LIST",
    "dateTimeFormat": "",
    "displayKey": {
      "field": "value"
    },
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "enableInlineEdit": true,
    "fieldType": "customFld",
    "filter": true,
    "hasMap": true,
    "jsonArrayKey": "",
    "key": "CUSTFIELD_96ENTITY_6_7780l",
    "keyname": "key",
    "label": "ENTITY",
    "limit": 0,
    "mandatory": true,
    "mappedModule": "",
    "maxLimit": 0,
    "minLimit": 0,
    "multi": true,
    "originalLabel": "ENTITY",
    "parentComponentId": 0,
    "parentFieldId": "",
    "parentId": 9,
    "readOnly": false,
    "seq": 13,
    "showInViewMode": false,
    "showProfileIcon": false,
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE"
    ],
    "sort": true,
    "sortType": "dsc",
    "type": "ARRAYKEYS",
    "updatedBy": 0,
    "width": 235,
    "isChecked": true,
    "searchRow": ""
  }
],
  6: [
  {
    "originalLabel": "Id",
    "label": "ID",
    "key": "code",
    "controlType": "TEXT",
    "hasMap": false,
    "cellCssClass": "badge-id",
    "width": 175,
    "deleted": false,
    "shownIn": [
      "TABLE"
    ],
    "sort": true,
    "sortType": "dsc",
    "showProfileIcon": false,
    "filter": true,
    "type": "",
    "keyname": "",
    "parentId": 9,
    "seq": 1,
    "jsonArrayKey": "",
    "fieldType": "defaultFld",
    "mandatory": false,
    "readOnly": false,
    "multi": false,
    "isDefault": true,
    "minLimit": 0,
    "maxLimit": 0,
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "c1b26480-568f-4fe3-ac83-8e0fb264e17c",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Name",
    "label": "Name",
    "key": "name",
    "controlType": "TEXT",
    "hasMap": false,
    "parentId": 9,
    "seq": 2,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": true,
    "jsonArrayKey": "",
    "minLimit": 3,
    "maxLimit": 500,
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "9150fc2c-2135-44b7-9c90-32a3f079ca3c",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Module",
    "label": "Module",
    "key": "moduleId",
    "controlType": "MODULE-LIST",
    "hasMap": true,
    "displayKey": {
      "field": "name"
    },
    "parentId": 9,
    "seq": 7,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "75c807ca-f752-4c49-9797-341ac059f3a8",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "State",
    "label": "State",
    "key": "state",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 4,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": true,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "d18d2971-8d3b-46e3-a48e-6a3531812e5f",
    "projectId": 6,
    "createdBy": 2,
    "limit": 0,
    "updatedBy": 71,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Labels",
    "label": "Labels",
    "key": "tags",
    "controlType": "LABEL",
    "multi": true,
    "hasMap": true,
    "displayKey": {
      "field": "name"
    },
    "jsonArrayKey": "",
    "parentId": 9,
    "seq": 8,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "",
    "type": "",
    "isDefault": true,
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "74dcab06-c2e4-44ab-85c6-cd55092b3ef8",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Category",
    "label": "Category",
    "key": "category",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 14,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "e3912929-83e0-4654-97d5-0071292be293",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Priority",
    "label": "Priority",
    "key": "priority",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 5,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "3893912d-c0e2-4c56-b6bd-baf3784e4791",
    "projectId": 6,
    "createdBy": 2,
    "limit": 0,
    "updatedBy": 71,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Test Case",
    "label": "Test Case",
    "key": "selectedTestCase",
    "controlType": "LIST",
    "multi": true,
    "hasMap": true,
    "displayKey": {
      "field": "name",
      "field2": "code"
    },
    "jsonArrayKey": "",
    "parentId": 9,
    "seq": 13,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "id",
    "type": "ARRAYKEYS",
    "isDefault": false,
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "c81d1965-d4de-4688-bea2-bc8c8b6ec4a8",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Created On",
    "label": "Created On",
    "key": "createdAt",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 29,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "shownIn": [
      "TABLE",
      "EDIT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "1223a601-63e3-42d1-92d7-f5482e683ceb",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Updated On",
    "label": "Updated On",
    "key": "updatedAt",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 30,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "shownIn": [
      "TABLE",
      "EDIT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "b3d819c1-80ac-42f2-871d-e75e3daa4c8b",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Closed Date",
    "label": "Closed Date",
    "key": "closedDate",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 23,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE"
    ],
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "7b497ce5-7b06-4c65-92c8-6cf84bb9ef3f",
    "projectId": 6,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "id": "97c877bb-0274-4827-88e0-784c7cfc9f39",
    "deleted": false,
    "projectId": 6,
    "cellCssClass": "",
    "controlType": "LIST",
    "createdBy": 71,
    "customFldType": "LIST",
    "dateTimeFormat": "",
    "displayKey": {
      "field": "value"
    },
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "enableInlineEdit": true,
    "fieldType": "customFld",
    "filter": true,
    "hasMap": true,
    "jsonArrayKey": "",
    "key": "CUSTFIELD_96ENTITY_6_2hk5a",
    "keyname": "key",
    "label": "ENTITY",
    "limit": 0,
    "mandatory": true,
    "mappedModule": "",
    "maxLimit": 0,
    "minLimit": 0,
    "multi": true,
    "originalLabel": "ENTITY",
    "parentComponentId": 0,
    "parentFieldId": "",
    "parentId": 9,
    "readOnly": false,
    "seq": 12,
    "showInViewMode": false,
    "showProfileIcon": false,
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE"
    ],
    "sort": true,
    "sortType": "dsc",
    "type": "ARRAYKEYS",
    "updatedBy": 0,
    "width": 235,
    "isChecked": true,
    "searchRow": ""
  }
],
};
