/**
 * Kenya (project 2) Defects column list captured with Sprint enabled.
 * PUT body is { defectFilter } only. No tokens.
 */
module.exports = [
  {
    "originalLabel": "Id",
    "label": "ID",
    "key": "code",
    "controlType": "TEXT",
    "hasMap": false,
    "cellCssClass": "badge-id",
    "width": 175,
    "deleted": false,
    "shownIn": [
      "TABLE"
    ],
    "sort": true,
    "sortType": "dsc",
    "showProfileIcon": false,
    "filter": true,
    "type": "",
    "keyname": "",
    "parentId": 9,
    "seq": 1,
    "jsonArrayKey": "",
    "fieldType": "defaultFld",
    "mandatory": false,
    "readOnly": false,
    "multi": false,
    "isDefault": true,
    "minLimit": 0,
    "maxLimit": 0,
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "8c484b37-fdbe-4478-a035-6ce5406ee463",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Name",
    "label": "Name",
    "key": "name",
    "controlType": "TEXT",
    "hasMap": false,
    "parentId": 9,
    "seq": 2,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": true,
    "jsonArrayKey": "",
    "minLimit": 3,
    "maxLimit": 500,
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "38e12065-99c9-4921-b404-42f4ee7cd739",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Module",
    "label": "Module",
    "key": "moduleId",
    "controlType": "MODULE-LIST",
    "hasMap": true,
    "displayKey": {
      "field": "name"
    },
    "parentId": 9,
    "seq": 7,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "185b1baa-732d-4487-87a6-986bb5d1971d",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "State",
    "label": "State",
    "key": "state",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 4,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": true,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "e452930f-eb3b-4260-a005-c0f6416f1627",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Labels",
    "label": "Labels",
    "key": "tags",
    "controlType": "LABEL",
    "multi": true,
    "hasMap": true,
    "displayKey": {
      "field": "name"
    },
    "jsonArrayKey": "",
    "parentId": 9,
    "seq": 8,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "",
    "type": "",
    "isDefault": true,
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "272b35b0-9096-4510-bf13-41add737d174",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Category",
    "label": "Category",
    "key": "category",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 13,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "a40eefcb-757f-425e-bb70-20ddb6fa07e7",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Priority",
    "label": "Priority",
    "key": "priority",
    "controlType": "LIST",
    "hasMap": true,
    "displayKey": {
      "field": "value"
    },
    "parentId": 9,
    "seq": 5,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "key",
    "type": "KEY",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "HEADER",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "ebbd5c7a-320f-4b65-b8f0-58fc07cae444",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Test Case",
    "label": "Test Case",
    "key": "selectedTestCase",
    "controlType": "LIST",
    "multi": true,
    "hasMap": true,
    "displayKey": {
      "field": "name",
      "field2": "code"
    },
    "jsonArrayKey": "",
    "parentId": 9,
    "seq": 12,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "id",
    "type": "ARRAYKEYS",
    "isDefault": false,
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": true,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "7cbff96e-eff4-4372-a9c0-13e0f10a515b",
    "projectId": 2,
    "createdBy": 2,
    "parentComponentId": 5,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Created On",
    "label": "Created On",
    "key": "createdAt",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 29,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "shownIn": [
      "TABLE",
      "EDIT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "cf17293d-47c3-42fa-9a3c-1cdc79674bc7",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Updated On",
    "label": "Updated On",
    "key": "updatedAt",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 30,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "shownIn": [
      "TABLE",
      "EDIT"
    ],
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "e4699f3f-3a97-4b16-89ca-3a3ea8ec0a1a",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Closed Date",
    "label": "Closed Date",
    "key": "closedDate",
    "controlType": "DATE",
    "hasMap": false,
    "parentId": 9,
    "seq": 22,
    "fieldType": "defaultFld",
    "mandatory": false,
    "deleted": false,
    "readOnly": true,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "displayKey": {
      "field": "name"
    },
    "keyname": "",
    "type": "",
    "isDefault": false,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE"
    ],
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "32e4fa0c-44ff-4af4-9233-8ed9b23c10c8",
    "projectId": 2,
    "createdBy": 2,
    "isChecked": true,
    "searchRow": ""
  },
  {
    "originalLabel": "Sprint",
    "label": "Sprint",
    "key": "iterationId",
    "controlType": "RELEASE-SPRINT",
    "hasMap": true,
    "displayKey": {
      "field": "name"
    },
    "parentId": 9,
    "seq": 10,
    "fieldType": "defaultFld",
    "mandatory": true,
    "deleted": false,
    "readOnly": false,
    "cellCssClass": "",
    "filter": true,
    "showProfileIcon": false,
    "sort": true,
    "sortType": "dsc",
    "width": 235,
    "keyname": "id",
    "type": "KEY",
    "isDefault": true,
    "jsonArrayKey": "",
    "shownIn": [
      "TABLE",
      "EDIT",
      "CREATE",
      "IMPORT"
    ],
    "enableInlineEdit": false,
    "enableColumnDrag": true,
    "enableColumnSearch": true,
    "id": "e73fce4f-005c-480b-9a47-bce672cbb4bf",
    "projectId": 2,
    "createdBy": 2,
    "parentComponentId": 12,
    "isChecked": true,
    "showLoader": false,
    "searchRow": ""
  }
];
