const ENTITIES = ["Life UG", "Gen UG", "Gen TZ"];

const MODULES = [
  "Accounts Payable",
  "Accounts Receivable",
  "Budgeting",
  "Cash & Bank Management",
  "Consolidation",
  "Credit Control",
  "Data Migration",
  "Data Migration>Data Migration -Functional",
  "Data Migration>Data Migration -Technical",
  "E2E Testcases",
  "E2E Testcases>E2E Account Payables",
  "E2E Testcases>E2E Accounts Receivables",
  "E2E Testcases>E2E Budgeting",
  "E2E Testcases>E2E Cash & Bank",
  "E2E Testcases>E2E Credit Control",
  "E2E Testcases>E2E Expense Management",
  "E2E Testcases>E2E Financial Reporting",
  "E2E Testcases>E2E Fixed Assets",
  "E2E Testcases>E2E General Ledger",
  "E2E Testcases>E2E Investment Management",
  "E2E Testcases>E2E Procurement",
  "E2E Testcases>E2E Tax Management",
  "Expense Management",
  "Financial Reporting",
  "Fixed Assets Management",
  "General Ledger",
  "Integrations",
  "Inventory Management",
  "Investment Management",
  "Investment Management>Investment Receipting",
  "Lease",
  "Payroll",
  "Payroll>FA Payroll",
  "Power BI Reporting",
  "Priority Integrations",
  "Procurement",
  "Procurement>Inventory",
  "Reinsurance",
  "Salary Review",
  "Salary Review>Bonus",
  "Tax Management",
];

module.exports = { ENTITIES, MODULES };
